## -----------------------------------------------------------------------------
## Authentication-Proxy configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2024-11-04
## -----------------------------------------------------------------------------

---
log_level: info

upstream: http://127.0.0.1:8080

http_server:
  host: 127.0.0.1
  port: 8081
  base_path:
  cert_file:
  key_file:
  read_timeout: 60s
  read_header_timeout: 10s

authentication:
  api_keys:
    - secret
  header_name: "Authorization"
  header_value_prefix: "Bearer"
  users:
    user: secret

rate_limit:
  max_burst_requests: 100
  max_concurrent_requests: 10
  request_queue_size: 50
  burst_duration: "1m"
  request_timeout: "30s"
...
